Repository Financial-Times/o-table, pull requests merged in 2020-07, with the labels that each got.

#210 Add option `data-o-table-preferred-sort-order`
  README.md
  src/js/Tables/BaseTable.js
  src/js/oTable.js
  test/BaseTable.test.js
Labels: component, release:patch

#211 Improve table sort order buttons.
  src/js/Tables/BaseTable.js
  src/scss/_sort.scss
  test/BaseTable.test.js
Labels: component, release:patch

#212 only run percy when a file has changed which can affect a demo
  .github/workflows/percy.yml
Labels: component, percy

#214 Add missing env to bring back bundle-size-cli PR comment
  .github/workflows/test-origami-component.yml
Labels: component
